package com.example.transactionrecovery;
import com.example.transactionrecovery.domain.*; import com.example.transactionrecovery.repository.*; import com.example.transactionrecovery.service.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.ActiveProfiles; import java.util.*; import static org.assertj.core.api.Assertions.*; import static com.example.transactionrecovery.domain.States.*;
@SpringBootTest @ActiveProfiles("test") class TransactionRecoveryIntegrationTest {@Autowired ApplicationCommandService commands;@Autowired OutboxPublisher publisher;@Autowired EventDeliveryService delivery;@Autowired SagaConsumer consumer;@Autowired ApplicationRepository apps;@Autowired SagaRepository sagas;@Autowired OutboxRepository outbox;@Autowired ProcessedEventRepository processed;
 @BeforeEach void clean(){processed.deleteAll();outbox.deleteAll();sagas.deleteAll();apps.deleteAll();}
 @Test void localTransactionCreatesApplicationSagaAndPendingOutbox(){var c=commands.start("tenant-a",new ApplicationCommandService.StartRequest("BASIC",false,0));assertThat(apps.findById(c.applicationId())).isPresent();assertThat(sagas.findById(c.sagaId()).orElseThrow().status).isEqualTo(SagaStatus.STARTED);assertThat(outbox.findById(c.eventId()).orElseThrow().status).isEqualTo(OutboxStatus.PENDING);}
 @Test void publishingAndConsumptionAreSeparatedAndDuplicateIsIgnored(){var c=commands.start("tenant-a",new ApplicationCommandService.StartRequest("BASIC",false,0));assertThat(publisher.publishPending()).isOne();assertThat(outbox.findById(c.eventId()).orElseThrow().status).isEqualTo(OutboxStatus.PUBLISHED);assertThat(sagas.findById(c.sagaId()).orElseThrow().status).isEqualTo(SagaStatus.STARTED);assertThat(delivery.consumeAvailable()).isOne();assertThat(sagas.findById(c.sagaId()).orElseThrow().status).isEqualTo(SagaStatus.COMPLETED);assertThat(consumer.consume(outbox.findById(c.eventId()).orElseThrow())).isFalse();assertThat(processed.count()).isOne();}
 @Test void businessFailureIsCompensated(){var c=commands.start("tenant-a",new ApplicationCommandService.StartRequest("BASIC",true,1));publisher.publishPending();delivery.consumeAvailable();Saga s=sagas.findById(c.sagaId()).orElseThrow();assertThat(s.status).isEqualTo(SagaStatus.COMPENSATED);assertThat(s.compensationAttempts).isEqualTo(2);assertThat(apps.findById(c.applicationId()).orElseThrow().status).isEqualTo(ApplicationStatus.CANCELLED);}
 @Test void exhaustedCompensationRequiresManualRecovery(){var c=commands.start("tenant-a",new ApplicationCommandService.StartRequest("BASIC",true,3));publisher.publishPending();delivery.consumeAvailable();assertThat(sagas.findById(c.sagaId()).orElseThrow().status).isEqualTo(SagaStatus.MANUAL_REQUIRED);}
 @Test void invalidTransitionIsBlocked(){Saga s=new Saga(UUID.randomUUID(),UUID.randomUUID(),"tenant-a");assertThatThrownBy(()->s.transition(SagaStatus.COMPLETED)).isInstanceOf(IllegalStateException.class);}
 @Test void tenantScopedLookupDoesNotRevealOtherTenant(){var c=commands.start("tenant-a",new ApplicationCommandService.StartRequest("BASIC",false,0));assertThat(sagas.findByIdAndTenantId(c.sagaId(),"tenant-b")).isEmpty();}
}
